import type { Metadata } from "next";
import { LegalPage } from "@/components/legal/legal-page";

export const metadata: Metadata = {
  title: "Privacy policy — PsychMind",
  description: "What PsychMind collects, why, and how we protect it.",
};

const privacyMailLink = (
  <a href="mailto:privacy@psychmind.co" className="underline hover:text-warm-900 transition-colors">
    privacy@psychmind.co
  </a>
);

export default function PrivacyPolicyPage() {
  return (
    <LegalPage
      title="Privacy policy"
      lastUpdated="March 2026"
      crossLinks={[
        { label: "COOKIE POLICY", href: "/cookie-policy" },
        { label: "TERMS AND CONDITIONS", href: "/terms" },
      ]}
      sections={[
        {
          heading: "1. Our commitment",
          paragraphs: [
            "PsychMind is built on trust. We collect only what we need, we never sell your data, and we treat the information you share with us as private by default. This policy explains what we collect, why, and how.",
          ],
        },
        {
          heading: "2. What we collect",
          paragraphs: [
            "Information you give us directly: name, email address, password, and any preferences you set during your search (such as specialty, location, or provider gender preference).",
            "Information generated by your use: pages visited, search queries made, sessions booked, and messages sent through the platform.",
            "Technical information: IP address, browser type, device type, and cookies (see our Cookie Policy for more detail).",
            "We do not collect sensitive medical records, diagnoses, or session content. What happens in your therapy sessions stays between you and your provider.",
          ],
        },
        {
          heading: "3. How we use your data",
          paragraphs: [
            "We use your information to: operate and improve the platform; match you with relevant providers; send you request confirmations and account notifications; respond to your support requests; and comply with legal obligations.",
            "We do not use your data for advertising. We do not sell, rent, or trade your personal information to any third party.",
          ],
        },
        {
          heading: "4. Who we share data with",
          paragraphs: [
            "We share data only where necessary: with the provider you choose to book with (name and contact details only); with payment processors to facilitate transactions; with hosting and infrastructure providers who are contractually bound to protect your data; and with authorities if required by law.",
          ],
        },
        {
          heading: "5. How long we keep your data",
          paragraphs: [
            "We retain your account data for as long as your account is active. If you delete your account, we will remove your personal data within 30 days, except where retention is required by law.",
          ],
        },
        {
          heading: "6. Your rights",
          paragraphs: [
            "Regardless of your location, we honour the following rights: the right to access the data we hold about you; the right to correct inaccurate data; the right to request deletion of your data; the right to withdraw consent at any time; and the right to receive your data in a portable format.",
            <>To exercise any of these rights, email us at {privacyMailLink}.</>,
          ],
        },
        {
          heading: "7. Data security",
          paragraphs: [
            "We use industry-standard encryption for data in transit and at rest. Access to personal data within our team is limited to those who need it to do their jobs. We conduct regular security reviews.",
          ],
        },
        {
          heading: "8. International transfers",
          paragraphs: [
            "If your data is transferred outside your country of residence, we ensure appropriate safeguards are in place. We will update this section with specifics as our infrastructure is finalized.",
          ],
        },
        {
          heading: "9. Children",
          paragraphs: [
            "PsychMind is not intended for anyone under the age of 18. We do not knowingly collect data from minors. If you believe a minor has registered, contact us immediately.",
          ],
        },
        {
          heading: "10. Changes to this policy",
          paragraphs: [
            "We will notify you by email of any significant changes to this policy. The date at the top of this page always reflects the most recent update.",
          ],
        },
        {
          heading: "11. Contact",
          paragraphs: [<>For any privacy-related questions: {privacyMailLink}.</>],
        },
      ]}
    />
  );
}
