// Sample providers for previewing search and public profiles before real
// providers are listed. Fictional people: names, bios, license numbers and
// addresses are invented. Photos are free-license Unsplash portraits
// (https://unsplash.com/license), hotlinked as Unsplash asks. Sara Oliisi,
// Shatiria Johnson and Monica Rios match the landing page; Sara's bio is the
// Figma copy (P1).
// Added and removed from Admin → Sample providers. Never bookable.

export type SampleProvider = {
  photo: string;
  first: string;
  last: string;
  pronouns: string;
  gender: "female" | "male" | "non_binary";
  title: string;
  years: number;
  fees: [individual: number, couples: number | null];
  sliding?: boolean;
  /** Defaults to accepting new clients. */
  full?: boolean;
  participants: string[];
  ages: string[];
  /** The first one is the main specialty. */
  specialties: string[];
  approaches: string[];
  languages: string[];
  education: [degree: string, school: string, year: number][];
  locations: { city: string; state: string; zip: string; formats: ("online" | "in_person")[]; practice?: string; address?: string }[];
  who: string;
  about: string;
};

const both = ["in_person", "online"] as ("online" | "in_person")[];
const online = ["online"] as ("online" | "in_person")[];

export const SAMPLE_PROVIDERS: SampleProvider[] = [
  {
    photo: "photo-1734365294784-00255163b97d",
    first: "Sara",
    last: "Oliisi",
    pronouns: "she/her",
    gender: "female",
    title: "Counselor, LMHC, M.S., B.S.",
    years: 9,
    fees: [120, 160],
    participants: ["individuals", "couples"],
    ages: ["adults"],
    specialties: ["anxiety", "relationships", "self_esteem", "life_transitions", "cultural_identity", "trauma_ptsd", "grief_loss"],
    approaches: ["cbt", "person_centered", "narrative"],
    languages: ["French", "English"],
    education: [["Ph.D. Clinical Psychology", "Université Mohammed V, Rabat", 2015]],
    locations: [{ city: "Miami", state: "FL", zip: "33131", formats: both, practice: "Brickell Counseling Studio", address: "1101 Brickell Ave, Suite 800" }],
    who: "I primarily work with adults (18+) on an individual basis, though I also offer couples sessions. My clients often come to me when they feel like they've tried to manage things on their own and need a different kind of support — not advice, but a space to think more clearly.\n\nI work especially well with people who are skeptical about therapy, or who have tried it before and felt it wasn't quite right. I take that seriously and we talk about it openly.",
    about:
      "I work with adults who feel stuck, overwhelmed, or disconnected from the life they want to be living. Many of my clients are navigating anxiety, stress, relationship challenges, or questions about identity — and they've often been carrying these things alone for a long time before reaching out.\n\nMy approach is collaborative and paced to your comfort. I don't believe therapy should feel like homework or a checklist. I believe it should feel like a conversation where you are genuinely heard — sometimes for the first time.",
  },
  {
    photo: "photo-1573497019418-b400bb3ab074",
    first: "Shatiria",
    last: "Johnson",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Clinical Psychologist, Psy.D.",
    years: 14,
    fees: [350, null],
    participants: ["individuals"],
    ages: ["adults", "seniors"],
    specialties: ["trauma_ptsd", "depression", "anxiety", "grief_loss", "self_esteem"],
    approaches: ["emdr", "cbt", "somatic"],
    languages: ["English"],
    education: [["Psy.D. Clinical Psychology", "Mercer University", 2011]],
    locations: [
      { city: "Atlanta", state: "GA", zip: "30306", formats: both, practice: "Virginia-Highland Psychology", address: "1050 N Highland Ave NE, Suite 3" },
      { city: "Charlotte", state: "NC", zip: "28203", formats: online },
    ],
    who: "I work with adults who have lived through hard things — a car accident, a loss that came too soon, years in a relationship that made them feel small — and who notice it still shows up in their body and their sleep.\n\nMany of my clients are high-functioning on the outside and exhausted underneath.",
    about:
      "I'm a licensed clinical psychologist trained in EMDR and trauma-focused CBT. We go at a pace that feels safe, and you stay in charge of what we talk about and when.\n\nMy goal is for you to feel more at home in your own life, not to relive the past for its own sake.",
  },
  {
    photo: "photo-1607746882042-944635dfe10e",
    first: "Monica",
    last: "Rios",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Marriage & Family Therapist, LMFT",
    years: 11,
    fees: [450, null],
    participants: ["individuals", "groups"],
    ages: ["adults"],
    specialties: ["relationships", "cultural_identity", "anxiety", "life_transitions", "parenting"],
    approaches: ["family_systems", "narrative", "attachment_based"],
    languages: ["Spanish", "English"],
    education: [["M.A. Marriage and Family Therapy", "Pepperdine University", 2013]],
    locations: [{ city: "Los Angeles", state: "CA", zip: "90026", formats: both, practice: "Echo Park Family Therapy", address: "1601 W Sunset Blvd, Suite 210" }],
    who: "I work with adults in the middle of change — a move, a new baby, a breakup, a career that no longer fits — and with first- and second-generation Latinx clients holding two cultures at once.\n\nI also run a small weekly group for women navigating family expectations.",
    about:
      "Sessions are bilingual in English and Spanish, whichever feels more like home that day. I draw on family systems and narrative therapy to help you see the patterns you inherited, and decide which ones you want to keep.",
  },
  {
    photo: "photo-1560250097-0b93528c311a",
    first: "Daniel",
    last: "Whitaker",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Clinical Social Worker, LCSW",
    years: 15,
    fees: [160, null],
    sliding: true,
    participants: ["individuals"],
    ages: ["adults"],
    specialties: ["depression", "anxiety", "burnout", "stress", "life_transitions"],
    approaches: ["cbt", "act", "psychodynamic"],
    languages: ["English"],
    education: [["M.S.W.", "University of Chicago, Crown Family School", 2009]],
    locations: [{ city: "Chicago", state: "IL", zip: "60614", formats: both, practice: "Lincoln Park Counseling", address: "2400 N Lincoln Ave, Suite 5" }],
    who: "I mostly see adults in their 30s to 50s who are good at holding everything together for everyone else — at work, at home — and have quietly run out of room for themselves.\n\nBurnout, low mood and the sense that life became a to-do list are what bring most people in.",
    about:
      "I'm practical and warm in equal measure. We'll make sense of what's keeping you stuck, try small changes between sessions, and adjust as we learn what helps.\n\nI've been a social worker for fifteen years, including eight in community mental health.",
  },
  {
    photo: "photo-1629425733761-caae3b5f2e50",
    first: "Arjun",
    last: "Mehta",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Professional Counselor, LPC",
    years: 7,
    fees: [130, null],
    participants: ["individuals"],
    ages: ["teens", "adults"],
    specialties: ["anxiety", "cultural_identity", "stress", "ocd", "self_esteem"],
    approaches: ["cbt", "act", "mindfulness"],
    languages: ["English", "Hindi", "Gujarati"],
    education: [["M.A. Clinical Mental Health Counseling", "University of Houston", 2017]],
    locations: [{ city: "Houston", state: "TX", zip: "77006", formats: both, practice: "Montrose Mind & Wellness", address: "3601 Montrose Blvd, Suite 304" }],
    who: "I work with teens and young adults dealing with anxiety, perfectionism and intrusive thoughts, and with South Asian clients balancing family expectations with their own path.\n\nMany of my clients have never talked to anyone about what goes on in their head.",
    about: "I use CBT and ACT to help you notice anxious loops and respond to them differently, without waiting to feel ready first. Sessions are available in English, Hindi and Gujarati.",
  },
  {
    photo: "photo-1699899657680-421c2c2d5064",
    first: "Hannah",
    last: "Lindqvist",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Mental Health Counselor, LMHC",
    years: 6,
    fees: [140, null],
    participants: ["individuals"],
    ages: ["teens", "adults"],
    specialties: ["eating_disorders", "self_esteem", "anxiety", "depression"],
    approaches: ["dbt", "cbt", "person_centered"],
    languages: ["English"],
    education: [["M.A. Counseling Psychology", "Seattle University", 2018]],
    locations: [
      { city: "Seattle", state: "WA", zip: "98122", formats: online },
      { city: "Portland", state: "OR", zip: "97214", formats: online },
    ],
    who: "I specialize in eating disorders and body image with teens and adults, including people who don't \"look sick\" and have been told they're fine.\n\nI also work with the anxiety and perfectionism that often come with them.",
    about:
      "Recovery isn't linear, and I won't pretend it is. I combine DBT skills with a lot of curiosity about what food and control have been doing for you.\n\nI'm happy to coordinate with your doctor or dietitian when that helps.",
  },
  {
    photo: "photo-1765005204058-10418f5123c5",
    first: "Imani",
    last: "Carter",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Clinical Social Worker, LCSW",
    years: 5,
    fees: [150, null],
    sliding: true,
    participants: ["individuals"],
    ages: ["adults"],
    specialties: ["life_transitions", "anxiety", "relationships", "self_esteem", "lgbtq"],
    approaches: ["person_centered", "narrative", "cbt"],
    languages: ["English"],
    education: [["M.S.W.", "Columbia University School of Social Work", 2019]],
    locations: [{ city: "Brooklyn", state: "NY", zip: "11215", formats: both, practice: "Park Slope Therapy Collective", address: "348 7th Ave, 2nd Floor" }],
    who: "I work with young adults figuring out who they are after college, after a breakup, after moving to a city where they don't know anyone yet.\n\nMany of my clients are Black women and queer folks who want a therapist they don't have to explain the basics to.",
    about:
      "My style is conversational and direct, with plenty of room for humor. We'll look at the stories you've been telling yourself and write some new ones.\n\nI keep a few sliding-scale spots open each month.",
  },
  {
    photo: "photo-1780733059130-fd07a8bc5256",
    first: "Claire",
    last: "Dubois",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Marriage & Family Therapist, LMFT",
    years: 12,
    fees: [170, 210],
    participants: ["individuals", "couples", "families"],
    ages: ["adults"],
    specialties: ["relationships", "parenting", "life_transitions", "anxiety"],
    approaches: ["attachment_based", "family_systems", "solution_focused"],
    languages: ["English", "French"],
    education: [["M.A. Couple and Family Therapy", "University of Denver", 2012]],
    locations: [{ city: "Denver", state: "CO", zip: "80206", formats: both, practice: "Cherry Creek Couples & Family", address: "250 Steele St, Suite 200" }],
    who: "Most of my clients are couples who still care about each other but keep having the same fight, and parents trying to stay a team through toddlers, teens or a divorce.\n\nI also see individuals who want to understand their patterns in relationships.",
    about: "I'm trained in Emotionally Focused Therapy, so we'll focus less on who's right and more on what each of you needs underneath the argument. Sessions are in English or French.",
  },
  {
    photo: "photo-1573496358961-3c82861ab8f4",
    first: "Ayanna",
    last: "Brooks",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Professional Counselor, LPC",
    years: 8,
    fees: [125, null],
    sliding: true,
    participants: ["individuals", "groups"],
    ages: ["adults", "seniors"],
    specialties: ["grief_loss", "depression", "trauma_ptsd", "chronic_illness"],
    approaches: ["person_centered", "narrative", "mindfulness"],
    languages: ["English"],
    education: [["M.A. Counseling Psychology", "Temple University", 2016]],
    locations: [{ city: "Philadelphia", state: "PA", zip: "19103", formats: both, practice: "Rittenhouse Grief & Counseling", address: "1930 Chestnut St, Suite 700" }],
    who: "I walk alongside people after a death, a diagnosis or a loss nobody else seems to count — a pregnancy, a friendship, the life you planned.\n\nI also facilitate a monthly grief group for adults who lost a parent.",
    about: "There's no right way to grieve and no deadline. I offer a steady, unhurried space where you can talk about the person or the life you're missing, and slowly find your footing again.",
  },
  {
    photo: "photo-1652471943570-f3590a4e52ed",
    first: "Marcus",
    last: "Bennett",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Clinical Social Worker, LCSW",
    years: 10,
    fees: [140, null],
    full: true,
    participants: ["individuals", "groups"],
    ages: ["adults"],
    specialties: ["addiction", "stress", "depression", "relationships"],
    approaches: ["cbt", "solution_focused", "mindfulness"],
    languages: ["English"],
    education: [["M.S.W.", "University of North Carolina at Charlotte", 2014]],
    locations: [{ city: "Charlotte", state: "NC", zip: "28203", formats: both, practice: "South End Recovery Counseling", address: "1440 S Tryon St, Suite 110" }],
    who: "I work with adults rethinking their relationship with alcohol or other substances, whether you want to stop completely, cut back, or just figure out what's going on.\n\nMany of my clients are men who have never been to therapy before.",
    about: "No lectures here. We'll get clear on what you want, what's getting in the way, and what's worked for you before.",
  },
  {
    photo: "photo-1627161683077-e34782c24d81",
    first: "Sofia",
    last: "Marchetti",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Mental Health Counselor, LMHC",
    years: 7,
    fees: [160, null],
    participants: ["individuals"],
    ages: ["teens", "adults"],
    specialties: ["ocd", "anxiety", "self_esteem"],
    approaches: ["cbt", "Exposure and response prevention (ERP)", "act"],
    languages: ["English", "Italian"],
    education: [["M.A. Mental Health Counseling", "Boston College", 2017]],
    locations: [{ city: "Boston", state: "MA", zip: "02116", formats: both, practice: "Back Bay Anxiety & OCD Center", address: "419 Boylston St, Suite 506" }],
    who: "I specialize in OCD and anxiety, including the less-talked-about forms: relationship doubts, health worries, intrusive thoughts that feel too scary to say out loud.\n\nI work with teens and adults.",
    about:
      "My main tool is exposure and response prevention, a well-studied approach for OCD, delivered gently and with your consent at every step.\n\nYou'll never be pushed into something you didn't agree to.",
  },
  {
    photo: "photo-1781888681811-332968760c2a",
    first: "Valeria",
    last: "Gutiérrez",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Professional Clinical Counselor, LPCC",
    years: 9,
    fees: [140, null],
    participants: ["individuals", "families"],
    ages: ["adults"],
    specialties: ["anxiety", "parenting", "life_transitions", "depression"],
    approaches: ["cbt", "mindfulness", "solution_focused"],
    languages: ["Spanish", "English"],
    education: [["M.A. Clinical Mental Health Counseling", "San Diego State University", 2015]],
    locations: [{ city: "San Diego", state: "CA", zip: "92103", formats: both, practice: "Hillcrest Family Counseling", address: "3900 Fifth Ave, Suite 320" }],
    who: "I work with moms in the years after having a baby, and with women juggling caregiving, work and everything else.\n\nAnxiety, guilt and the feeling of losing yourself are the most common reasons people reach out to me.",
    about: "Sessions are bilingual and practical. We'll make space for how hard this season is, and build small routines that give you back some breathing room.",
  },
  {
    photo: "photo-1760543998147-117ae5649c5c",
    first: "Rebecca",
    last: "Holt",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Psychologist, Ph.D.",
    years: 16,
    fees: [200, null],
    participants: ["individuals"],
    ages: ["adults", "seniors"],
    specialties: ["depression", "bipolar", "anxiety", "chronic_illness", "sleep"],
    approaches: ["cbt", "act", "psychodynamic"],
    languages: ["English"],
    education: [["Ph.D. Clinical Psychology", "University of Minnesota", 2008]],
    locations: [{ city: "Minneapolis", state: "MN", zip: "55408", formats: both, practice: "Uptown Psychology", address: "1409 W Lake St, Suite 2" }],
    who: "I work with adults living with depression, bipolar disorder and long-term health conditions, including people who have tried several therapists or medications and feel worn down by the search.",
    about:
      "I'm a licensed psychologist with sixteen years in hospital and private practice settings, and I'm happy to work alongside your psychiatrist or primary care doctor.\n\nTogether we'll focus on steadier days, better sleep and more of the life you care about.",
  },
  {
    photo: "photo-1500648767791-00dcc994a43e",
    first: "Ethan",
    last: "Caldwell",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Marriage & Family Therapist, LMFT",
    years: 8,
    fees: [150, 190],
    participants: ["individuals", "couples"],
    ages: ["adults"],
    specialties: ["relationships", "lgbtq", "self_esteem", "anxiety"],
    approaches: ["attachment_based", "person_centered", "narrative"],
    languages: ["English"],
    education: [["M.A. Marriage, Couple and Family Therapy", "Lewis & Clark College", 2016]],
    locations: [{ city: "Portland", state: "OR", zip: "97214", formats: both, practice: "Hawthorne Relationship Therapy", address: "3530 SE Hawthorne Blvd" }],
    who: "I work with couples of all kinds, and with gay and bisexual men exploring relationships, identity and the pressure to have it all figured out.\n\nCommunication, trust after betrayal and opening up emotionally are common themes.",
    about:
      "I'm warm, curious and honest. In couples work I stay balanced and won't take sides, but I will name what I see.\n\nIndividually, I'll help you understand why you show up the way you do in relationships.",
  },
  {
    photo: "photo-1595211877493-41a4e5f236b3",
    first: "Jamal",
    last: "Pierce",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Professional Counselor, LPC",
    years: 6,
    fees: [120, null],
    sliding: true,
    participants: ["individuals"],
    ages: ["teens", "adults"],
    specialties: ["stress", "anxiety", "depression", "cultural_identity", "burnout"],
    approaches: ["cbt", "solution_focused", "mindfulness"],
    languages: ["English"],
    education: [["M.S. Clinical Mental Health Counseling", "Georgia State University", 2018]],
    locations: [{ city: "Decatur", state: "GA", zip: "30030", formats: both, practice: "Decatur Square Counseling", address: "125 E Trinity Pl, Suite 208" }],
    who: "I work with Black men and young adults who are carrying a lot and talking about very little of it — pressure at work, family responsibilities, racism, grief.\n\nA lot of my clients were raised to just handle it.",
    about: "Therapy with me feels like a real conversation, not a clinical interview. We'll build practical tools for stress and anger, and make space for what you haven't had room to feel.",
  },
  {
    photo: "photo-1580894732444-8ecded7900cd",
    first: "Molly",
    last: "Gallagher",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Independent Clinical Social Worker, LICSW",
    years: 7,
    fees: [155, null],
    participants: ["individuals"],
    ages: ["teens", "adults"],
    specialties: ["adhd", "anxiety", "self_esteem", "burnout"],
    approaches: ["cbt", "solution_focused", "mindfulness"],
    languages: ["English"],
    education: [["M.S.W.", "Boston University School of Social Work", 2017]],
    locations: [{ city: "Cambridge", state: "MA", zip: "02139", formats: both, practice: "Central Square ADHD Clinic", address: "678 Massachusetts Ave, Suite 401" }],
    who: "I work with teens and adults with ADHD, diagnosed or suspected — especially women who were missed as kids and spent years thinking they just needed to try harder.",
    about: "We'll swap shame for strategy: routines that fit your brain, ways to handle overwhelm, and a lot less self-criticism. I have ADHD myself, so I won't be surprised if you're running late.",
  },
  {
    photo: "photo-1507003211169-0a1dd7228f2d",
    first: "Gabriel",
    last: "Santos",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Marriage & Family Therapist, LMFT",
    years: 9,
    fees: [175, 220],
    participants: ["individuals", "couples", "families"],
    ages: ["teens", "adults"],
    specialties: ["cultural_identity", "relationships", "depression", "lgbtq", "life_transitions"],
    approaches: ["narrative", "family_systems", "person_centered"],
    languages: ["English", "Tagalog"],
    education: [["M.A. Counseling Psychology (MFT)", "University of San Francisco", 2015]],
    locations: [{ city: "San Francisco", state: "CA", zip: "94110", formats: both, practice: "Mission Family Therapy", address: "2940 16th St, Suite 202" }],
    who: "I work with Filipino and Asian American individuals and families, LGBTQ+ adults, and couples from different cultures learning to blend their families, traditions and expectations.",
    about: "My approach is relational and grounded in culture. We'll honor where you come from while making room for who you're becoming. Sessions in English or Tagalog.",
  },
  {
    photo: "photo-1573496359142-b8d87734a5a2",
    first: "Natalie",
    last: "Brennan",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Professional Counselor, LPC",
    years: 8,
    fees: [145, null],
    participants: ["individuals"],
    ages: ["adults"],
    specialties: ["trauma_ptsd", "anxiety", "relationships", "self_esteem"],
    approaches: ["emdr", "somatic", "cbt"],
    languages: ["English"],
    education: [["M.A. Clinical Mental Health Counseling", "Arizona State University", 2016]],
    locations: [{ city: "Phoenix", state: "AZ", zip: "85004", formats: both, practice: "Roosevelt Row Trauma Therapy", address: "918 N 2nd St, Suite 4" }],
    who: "I work with adults recovering from relational trauma — emotionally abusive relationships, difficult childhoods, workplaces that wore them down — who find themselves stuck in people-pleasing or always on alert.",
    about: "I'm EMDR-trained and pay attention to what your body is telling us, not just your thoughts. We'll start by building a sense of safety and go from there, at your pace.",
  },
  {
    photo: "photo-1573497019940-1c28c88b4f3e",
    first: "Elena",
    last: "Vargas",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Clinical Psychologist, Psy.D.",
    years: 18,
    fees: [190, null],
    full: true,
    participants: ["individuals", "families"],
    ages: ["adults", "seniors"],
    specialties: ["trauma_ptsd", "cultural_identity", "depression", "grief_loss"],
    approaches: ["emdr", "cbt", "narrative"],
    languages: ["Spanish", "English"],
    education: [["Psy.D. Clinical Psychology", "Alliant International University", 2006]],
    locations: [{ city: "Tucson", state: "AZ", zip: "85719", formats: both, practice: "Desert Bloom Psychology", address: "2030 E Speedway Blvd, Suite 112" }],
    who: "I work with adults and families affected by trauma, immigration and loss, including people who have been separated from loved ones or are rebuilding life in a new country.",
    about: "I'm a bilingual psychologist and have spent eighteen years in community clinics and private practice. My practice is currently full.",
  },
  {
    photo: "photo-1519085360753-af0119f7cbe7",
    first: "Nathan",
    last: "Cole",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Mental Health Counselor, LMHC",
    years: 6,
    fees: [180, null],
    participants: ["individuals"],
    ages: ["adults"],
    specialties: ["burnout", "anxiety", "stress", "life_transitions"],
    approaches: ["cbt", "act", "solution_focused"],
    languages: ["English"],
    education: [["M.A. Mental Health Counseling", "New York University", 2018]],
    locations: [{ city: "New York", state: "NY", zip: "10011", formats: both, practice: "Chelsea Counseling Group", address: "215 W 14th St, Suite 4R" }],
    who: "I mostly work with professionals in finance, law, tech and medicine who are good at their jobs and quietly miserable.\n\nBurnout, imposter feelings and Sunday-night dread are familiar territory.",
    about: "Evening sessions are available. We'll look honestly at what your career is costing you and what you want instead, and build boundaries that survive contact with your inbox.",
  },
  {
    photo: "photo-1611432579699-484f7990b127",
    first: "Kiara",
    last: "Thompson",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Clinical Social Worker, LCSW",
    years: 7,
    fees: [130, null],
    sliding: true,
    participants: ["individuals", "groups"],
    ages: ["teens", "adults"],
    specialties: ["depression", "anxiety", "self_esteem", "relationships"],
    approaches: ["person_centered", "cbt", "mindfulness"],
    languages: ["English"],
    education: [["M.S.W.", "University of Maryland School of Social Work", 2017]],
    locations: [{ city: "Baltimore", state: "MD", zip: "21201", formats: both, practice: "Mount Vernon Wellness", address: "10 E Read St, Suite 3" }],
    who: "I work with teens and young adults navigating depression, anxiety and big life decisions, and I run a group for Black college students.\n\nSelf-worth and family relationships come up a lot.",
    about: "I aim to be the kind of therapist I would have wanted at nineteen: real, encouraging and honest. We'll go at your pace.",
  },
  {
    photo: "photo-1494790108377-be9c29b29330",
    first: "Emily",
    last: "Hartman",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Professional Counselor, LPC",
    years: 4,
    fees: [110, null],
    participants: ["individuals"],
    ages: ["teens", "adults"],
    specialties: ["anxiety", "self_esteem", "relationships", "life_transitions"],
    approaches: ["cbt", "mindfulness", "person_centered"],
    languages: ["English"],
    education: [["M.Ed. Human Development Counseling", "Vanderbilt University", 2020]],
    locations: [{ city: "Nashville", state: "TN", zip: "37203", formats: both, practice: "Music Row Counseling", address: "1030 16th Ave S, Suite 2" }],
    who: "I work with teens and adults in their twenties dealing with anxiety, social worries and the pressure to have life figured out by now.",
    about: "Sessions are relaxed but focused. You'll leave with something concrete to try, and we'll keep what works and drop what doesn't.",
  },
  {
    photo: "photo-1611432579402-7037e3e2c1e4",
    first: "Danielle",
    last: "Morgan",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Marriage & Family Therapist, LMFT",
    years: 9,
    fees: [150, 180],
    participants: ["individuals", "couples", "families"],
    ages: ["children", "teens", "adults"],
    specialties: ["parenting", "relationships", "adhd", "anxiety"],
    approaches: ["family_systems", "solution_focused", "cbt"],
    languages: ["English"],
    education: [["M.S. Marriage and Family Therapy", "Texas Woman's University", 2015]],
    locations: [{ city: "Dallas", state: "TX", zip: "75204", formats: both, practice: "Uptown Family Therapy", address: "3131 McKinney Ave, Suite 600" }],
    who: "I work with families of children and teens — especially kids with ADHD or big emotions — and with parents who feel like they've tried everything.\n\nI also see couples adjusting to parenthood.",
    about: "Family sessions are practical and kind. We'll focus on connection first, then on routines and consistency that actually stick in a busy household.",
  },
  {
    photo: "photo-1580489944761-15a19d654956",
    first: "Leah",
    last: "Rosenberg",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Clinical Social Worker, LCSW",
    years: 10,
    fees: [190, null],
    participants: ["individuals"],
    ages: ["adults"],
    specialties: ["anxiety", "relationships", "self_esteem", "depression"],
    approaches: ["psychodynamic", "person_centered", "mindfulness"],
    languages: ["English", "Hebrew"],
    education: [["M.S.W.", "Hunter College Silberman School of Social Work", 2014]],
    locations: [
      { city: "New York", state: "NY", zip: "10024", formats: both, practice: "Upper West Side Psychotherapy", address: "2350 Broadway, Suite 712" },
      { city: "Jersey City", state: "NJ", zip: "07302", formats: online },
    ],
    who: "I work with adults who are self-aware, thoughtful and still stuck — people who can explain their patterns perfectly and still repeat them.\n\nRelationships, anxiety and family dynamics are common themes.",
    about: "My approach is psychodynamic: we'll take our time understanding where your patterns come from, so change goes deeper than a new set of tips. Sessions are in English or Hebrew.",
  },
  {
    photo: "photo-1563132337-f159f484226c",
    first: "Chioma",
    last: "Adeyemi",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Professional Counselor, LPC",
    years: 5,
    fees: [120, null],
    sliding: true,
    participants: ["individuals"],
    ages: ["teens", "adults"],
    specialties: ["cultural_identity", "anxiety", "depression", "self_esteem"],
    approaches: ["narrative", "cbt", "person_centered"],
    languages: ["English", "Yoruba"],
    education: [["M.A. Counseling", "St. Edward's University", 2019]],
    locations: [{ city: "Austin", state: "TX", zip: "78701", formats: both, practice: "Congress Avenue Counseling", address: "815 Brazos St, Suite 400" }],
    who: "I work with African immigrants, children of immigrants and international students navigating two cultures, family expectations and the loneliness of being far from home.",
    about: "I'll understand the context without you having to explain it. Together we'll sort out what's yours to carry and what you can put down.",
  },
  {
    photo: "photo-1618085219724-c59ba48e08cd",
    first: "Isabel",
    last: "Moreno",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Clinical Social Worker, LCSW",
    years: 11,
    fees: [120, null],
    sliding: true,
    participants: ["individuals", "families"],
    ages: ["children", "teens", "adults"],
    specialties: ["depression", "parenting", "anxiety", "trauma_ptsd"],
    approaches: ["cbt", "family_systems", "person_centered"],
    languages: ["Spanish", "Portuguese", "English"],
    education: [["M.S.W.", "University of Central Florida", 2013]],
    locations: [{ city: "Orlando", state: "FL", zip: "32801", formats: both, practice: "Lake Eola Family Counseling", address: "220 E Central Blvd, Suite 3" }],
    who: "I work with Latino and Brazilian families, children and teens, and parents trying to support a struggling kid while dealing with their own stress.\n\nSessions in English, Spanish or Portuguese.",
    about: "I've worked in schools and community clinics for over a decade. I believe in involving the family when it helps, and I'll always explain what we're doing and why.",
  },
  {
    photo: "photo-1507152832244-10d45c7eda57",
    first: "Naomi",
    last: "Ellis",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Psychologist, Ph.D.",
    years: 15,
    fees: [210, null],
    participants: ["individuals"],
    ages: ["adults", "seniors"],
    specialties: ["trauma_ptsd", "depression", "chronic_illness", "grief_loss"],
    approaches: ["cbt", "act", "emdr"],
    languages: ["English"],
    education: [["Ph.D. Clinical Psychology", "Duke University", 2009]],
    locations: [{ city: "Durham", state: "NC", zip: "27701", formats: both, practice: "Bull City Health Psychology", address: "305 E Chapel Hill St, Suite 210" }],
    who: "I work with adults living with chronic illness or pain, and with survivors of medical trauma who feel dismissed by doctors and exhausted by appointments.",
    about: "I'm a licensed psychologist with a background in health psychology. We'll work on the emotional weight of living in a body that needs a lot of care, and on getting back to what matters to you.",
  },
  {
    photo: "photo-1561406636-b80293969660",
    first: "Tasha",
    last: "Robinson",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Master Social Worker (Clinical), LMSW",
    years: 6,
    fees: [100, null],
    sliding: true,
    participants: ["individuals", "families"],
    ages: ["teens", "adults", "seniors"],
    specialties: ["grief_loss", "depression", "relationships", "stress"],
    approaches: ["person_centered", "narrative", "solution_focused"],
    languages: ["English"],
    education: [["M.S.W.", "Wayne State University", 2018]],
    locations: [{ city: "Detroit", state: "MI", zip: "48201", formats: both, practice: "Midtown Family Services", address: "4219 Woodward Ave, Suite 200" }],
    who: "I work with families and individuals after loss, including violent or sudden loss, and with young people stepping into caregiving roles before they're ready.",
    about: "I grew up in Detroit and care deeply about this community. My sessions are grounded, honest and unhurried, and I'll meet you where you are.",
  },
  {
    photo: "photo-1638727295415-286409421143",
    first: "Zara",
    last: "Mitchell",
    pronouns: "she/they",
    gender: "female",
    title: "Licensed Professional Clinical Counselor, LPCC",
    years: 5,
    fees: [110, null],
    sliding: true,
    participants: ["individuals", "groups"],
    ages: ["teens", "adults"],
    specialties: ["lgbtq", "self_esteem", "anxiety", "depression", "cultural_identity"],
    approaches: ["narrative", "person_centered", "act"],
    languages: ["English"],
    education: [["M.A. Clinical Mental Health Counseling", "The Ohio State University", 2019]],
    locations: [{ city: "Columbus", state: "OH", zip: "43215", formats: both, practice: "Short North Affirming Therapy", address: "1000 N High St, Suite 3" }],
    who: "I work with queer and trans teens and adults, especially people of color, around identity, coming out, family relationships and the everyday stress of being visible.",
    about: "My office is a space where you won't have to educate your therapist. I'm affirming and collaborative, and I'll celebrate the wins with you.",
  },
  {
    photo: "photo-1581065178047-8ee15951ede6",
    first: "Jenny",
    last: "Nguyen",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Marriage & Family Therapist, LMFT",
    years: 10,
    fees: [165, 200],
    participants: ["individuals", "couples", "families"],
    ages: ["adults"],
    specialties: ["relationships", "cultural_identity", "anxiety", "parenting"],
    approaches: ["family_systems", "attachment_based", "cbt"],
    languages: ["Vietnamese", "English"],
    education: [["M.A. Marriage and Family Therapy", "Santa Clara University", 2014]],
    locations: [{ city: "Oakland", state: "CA", zip: "94612", formats: both, practice: "Lake Merritt Family Therapy", address: "1999 Harrison St, Suite 1800" }],
    who: "I work with Vietnamese and Asian American families, couples navigating cultural differences, and adult children trying to set boundaries with parents they love.",
    about: "Sessions are available in Vietnamese or English. We'll find a way to honor family without losing yourself, and to talk about things your family may never have had words for.",
  },
  {
    photo: "photo-1758600587839-56ba05596c69",
    first: "Grace",
    last: "Kim",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Professional Counselor, LPC",
    years: 6,
    fees: [160, null],
    participants: ["individuals"],
    ages: ["adults"],
    specialties: ["anxiety", "burnout", "self_esteem", "cultural_identity"],
    approaches: ["cbt", "act", "mindfulness"],
    languages: ["Korean", "English"],
    education: [["M.A. Counseling", "George Washington University", 2018]],
    locations: [
      { city: "Arlington", state: "VA", zip: "22201", formats: both, practice: "Clarendon Counseling", address: "3033 Wilson Blvd, Suite 700" },
      { city: "Bethesda", state: "MD", zip: "20814", formats: online },
    ],
    who: "I work with Korean American and Asian American professionals dealing with anxiety, perfectionism and burnout, and with people who feel they're living on autopilot.",
    about: "I blend CBT and ACT with mindfulness. You'll learn to notice the pressure without letting it run your life. Sessions in English or Korean.",
  },
  {
    photo: "photo-1735424080768-8730f9c8a0e9",
    first: "Mei",
    last: "Zhang",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Mental Health Counselor, LMHC",
    years: 8,
    fees: [150, 185],
    participants: ["individuals", "couples"],
    ages: ["adults"],
    specialties: ["anxiety", "relationships", "cultural_identity", "sleep"],
    approaches: ["cbt", "mindfulness", "solution_focused"],
    languages: ["Mandarin", "Cantonese", "English"],
    education: [["M.A. Clinical Psychology", "Seattle Pacific University", 2016]],
    locations: [{ city: "Bellevue", state: "WA", zip: "98004", formats: both, practice: "Eastside Counseling Center", address: "10900 NE 8th St, Suite 1400" }],
    who: "I work with Chinese-speaking adults and couples, international students and tech workers dealing with anxiety, insomnia, relationship stress and life far from family.",
    about: "Sessions are in Mandarin, Cantonese or English. I'm structured and practical, and I'll give you tools you can use the same week.",
  },
  {
    photo: "photo-1581065178026-390bc4e78dad",
    first: "Anna",
    last: "Reyes",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Clinical Social Worker, LCSW",
    years: 12,
    fees: [170, 210],
    participants: ["individuals", "couples"],
    ages: ["adults"],
    specialties: ["relationships", "anxiety", "depression", "parenting"],
    approaches: ["cbt", "family_systems", "person_centered"],
    languages: ["English", "Tagalog"],
    education: [["M.S.W.", "Rutgers University", 2012]],
    locations: [
      { city: "Jersey City", state: "NJ", zip: "07302", formats: both, practice: "Exchange Place Counseling", address: "30 Montgomery St, Suite 1210" },
      { city: "New York", state: "NY", zip: "10004", formats: online },
    ],
    who: "I work with adults and couples juggling demanding careers, aging parents and young kids, and with healthcare workers carrying the stress of caring for everyone else.",
    about: "I spent years as a hospital social worker before private practice. I'm calm, organized and good at helping overwhelmed people find the next small step.",
  },
  {
    photo: "photo-1787023892103-c6fd29182050",
    first: "Amina",
    last: "Rahman",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Professional Counselor, LPC",
    years: 7,
    fees: [120, null],
    sliding: true,
    participants: ["individuals", "couples", "families"],
    ages: ["teens", "adults"],
    specialties: ["anxiety", "cultural_identity", "relationships", "depression"],
    approaches: ["cbt", "person_centered", "mindfulness"],
    languages: ["English", "Bengali"],
    education: [["M.A. Counseling", "Eastern Michigan University", 2017]],
    locations: [{ city: "Ann Arbor", state: "MI", zip: "48104", formats: both, practice: "Huron Valley Counseling", address: "2350 Washtenaw Ave, Suite 6" }],
    who: "I work with Muslim individuals, couples and families who want therapy that respects their faith and culture, and with young adults navigating identity between two worlds.",
    about: "I integrate faith when you'd like it to be part of the conversation, and never when you don't. Sessions in English or Bengali.",
  },
  {
    photo: "photo-1614273867161-22da2cd8ab39",
    first: "Camila",
    last: "Ortiz",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Marriage & Family Therapist, LMFT",
    years: 4,
    fees: [130, 160],
    participants: ["individuals", "couples"],
    ages: ["adults"],
    specialties: ["relationships", "self_esteem", "anxiety", "lgbtq"],
    approaches: ["attachment_based", "person_centered", "narrative"],
    languages: ["Spanish", "English"],
    education: [["M.S. Marriage and Family Therapy", "University of Nevada, Las Vegas", 2020]],
    locations: [{ city: "Las Vegas", state: "NV", zip: "89101", formats: both, practice: "Arts District Therapy", address: "1025 S 1st St, Suite 120" }],
    who: "I work with young adults and couples on dating, attachment, breakups and building relationships that feel secure, including LGBTQ+ couples.",
    about: "I'm warm and down to earth. We'll explore how your early relationships shaped the way you love now, and practice new ways of showing up.",
  },
  {
    photo: "photo-1665062173657-3912ae7991e0",
    first: "Margaret",
    last: "O'Brien",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Clinical Social Worker, LCSW",
    years: 30,
    fees: [140, 170],
    participants: ["individuals", "couples"],
    ages: ["adults", "seniors"],
    specialties: ["grief_loss", "life_transitions", "depression", "chronic_illness"],
    approaches: ["person_centered", "narrative", "psychodynamic"],
    languages: ["English"],
    education: [["M.S.W.", "University of Pittsburgh", 1994]],
    locations: [{ city: "Pittsburgh", state: "PA", zip: "15213", formats: both, practice: "Oakland Counseling Associates", address: "3600 Forbes Ave, Suite 2" }],
    who: "I work with older adults and couples facing retirement, illness, the loss of a spouse or the quiet questions that come later in life, and with adult children caring for aging parents.",
    about: "After thirty years as a social worker, mostly in hospice and hospital settings, I bring patience and a lot of respect for the lives people have lived. Telehealth is available for those who can't easily travel.",
  },
  {
    photo: "photo-1730295004113-a9293b379cbd",
    first: "Judith",
    last: "Kaplan",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Psychologist, Ph.D.",
    years: 35,
    fees: [220, 260],
    participants: ["individuals", "couples"],
    ages: ["adults", "seniors"],
    specialties: ["depression", "anxiety", "relationships", "grief_loss"],
    approaches: ["psychodynamic", "person_centered"],
    languages: ["English", "Hebrew"],
    education: [["Ph.D. Clinical Psychology", "Boston University", 1989]],
    locations: [{ city: "Brookline", state: "MA", zip: "02445", formats: both, practice: "Coolidge Corner Psychotherapy", address: "1330 Beacon St, Suite 304" }],
    who: "I work with adults of every age who want to understand themselves more deeply — long-standing depression, relationship patterns, and the turning points that make you rethink your life.",
    about: "I practice long-term psychodynamic therapy and have been doing this work for thirty-five years. I believe the relationship itself is where much of the change happens.",
  },
  {
    photo: "photo-1781002220057-a56f0df3c49f",
    first: "Linda",
    last: "Sorensen",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Professional Counselor, LPC",
    years: 22,
    fees: [150, null],
    participants: ["individuals", "groups"],
    ages: ["adults", "seniors"],
    specialties: ["anxiety", "stress", "chronic_illness", "sleep"],
    approaches: ["mindfulness", "somatic", "act"],
    languages: ["English"],
    education: [["M.A. Counseling Psychology", "Naropa University", 2002]],
    locations: [{ city: "Boulder", state: "CO", zip: "80302", formats: both, practice: "Pearl Street Mindfulness Counseling", address: "1600 Pearl St, Suite 210" }],
    who: "I work with adults dealing with anxiety, chronic stress and health worries, and I lead mindfulness groups for people who want calmer minds and kinder self-talk.",
    about: "My approach blends mindfulness, body awareness and acceptance-based therapy. Sessions are calm and grounded, and we'll find practices that fit your actual life.",
  },
  {
    photo: "photo-1590905707155-17c680dd7867",
    first: "Lakshmi",
    last: "Iyer",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Psychologist, Ph.D.",
    years: 28,
    fees: [200, 240],
    participants: ["individuals", "couples", "families"],
    ages: ["adults", "seniors"],
    specialties: ["depression", "cultural_identity", "relationships", "life_transitions"],
    approaches: ["cbt", "family_systems", "psychodynamic"],
    languages: ["English", "Hindi", "Tamil"],
    education: [["Ph.D. Counseling Psychology", "Rutgers University", 1996]],
    locations: [{ city: "Princeton", state: "NJ", zip: "08540", formats: both, practice: "Nassau Street Psychology", address: "20 Nassau St, Suite 211" }],
    who: "I work with South Asian individuals and families across generations, from young adults negotiating marriage and career to elders adjusting to life in a new country.",
    about: "I've practiced for almost thirty years and understand how family, honor and duty shape what people feel allowed to say. Sessions in English, Hindi or Tamil.",
  },
  {
    photo: "photo-1566616213894-2d4e1baee5d8",
    first: "Barbara",
    last: "Collins",
    pronouns: "she/her",
    gender: "female",
    title: "Licensed Marriage & Family Therapist, LMFT",
    years: 26,
    fees: [160, 200],
    participants: ["individuals", "couples", "families"],
    ages: ["adults", "seniors"],
    specialties: ["relationships", "grief_loss", "parenting", "life_transitions"],
    approaches: ["family_systems", "solution_focused", "person_centered"],
    languages: ["English"],
    education: [["M.A. Marriage and Family Therapy", "California State University, Sacramento", 1998]],
    locations: [{ city: "Sacramento", state: "CA", zip: "95814", formats: both, practice: "Capitol Family Therapy", address: "1201 K St, Suite 940" }],
    who: "I work with couples in long marriages, blended families, and grandparents stepping in to raise grandchildren.\n\nEmpty nests, remarriage and family conflict are familiar ground.",
    about: "Twenty-six years of practice have taught me that most families want the same thing: to feel close without losing themselves. We'll work toward that together.",
  },
  {
    photo: "photo-1676989880361-091e12efc056",
    first: "David",
    last: "Kowalski",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Professional Counselor, LPC",
    years: 8,
    fees: [130, 165],
    participants: ["individuals", "couples"],
    ages: ["adults"],
    specialties: ["depression", "anxiety", "relationships", "self_esteem"],
    approaches: ["act", "cbt", "person_centered"],
    languages: ["English", "Polish"],
    education: [["M.S. Clinical Mental Health Counseling", "Marquette University", 2016]],
    locations: [{ city: "Milwaukee", state: "WI", zip: "53202", formats: both, practice: "Third Ward Counseling", address: "333 N Water St, Suite 300" }],
    who: "I work with adults who feel flat, stuck or disconnected, and with men who want to be more present partners and fathers but don't always know where to start.",
    about: "I'm easygoing and straightforward. We'll clarify what matters to you and take steps toward it, even while the hard feelings are still around.",
  },
  {
    photo: "photo-1568602471122-7832951cc4c5",
    first: "Ben",
    last: "Adler",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Clinical Social Worker, LCSW",
    years: 9,
    fees: [175, null],
    participants: ["individuals"],
    ages: ["teens", "adults"],
    specialties: ["adhd", "anxiety", "burnout", "self_esteem"],
    approaches: ["cbt", "solution_focused", "mindfulness"],
    languages: ["English"],
    education: [["M.S.W.", "USC Suzanne Dworak-Peck School of Social Work", 2015]],
    locations: [{ city: "Santa Monica", state: "CA", zip: "90405", formats: both, practice: "Ocean Park ADHD Therapy", address: "2701 Ocean Park Blvd, Suite 140" }],
    who: "I work with creatives and professionals with ADHD who are brilliant in bursts and exhausted by the rest — missed deadlines, half-finished projects and the shame that comes with them.",
    about: "Sessions are part coaching, part therapy. We'll build systems that work with your brain instead of against it, and untangle the story that you're lazy. You're not.",
  },
  {
    photo: "photo-1770510067230-1059f0776b3a",
    first: "Kevin",
    last: "Park",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Mental Health Counselor, LMHC",
    years: 4,
    fees: [115, null],
    participants: ["individuals"],
    ages: ["teens", "adults"],
    specialties: ["anxiety", "stress", "self_esteem", "life_transitions"],
    approaches: ["cbt", "act"],
    languages: ["English", "Korean"],
    education: [["M.A. Clinical Mental Health Counseling", "University of South Florida", 2020]],
    locations: [{ city: "Tampa", state: "FL", zip: "33602", formats: online }],
    who: "I work with college students and young professionals dealing with anxiety, social pressure and the weight of other people's expectations.",
    about: "I'm a younger therapist who gets the world you're living in, from group chats to job hunting. Sessions are focused and collaborative.",
  },
  {
    photo: "photo-1780732997580-df3992363434",
    first: "Richard",
    last: "Hale",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Psychologist, Psy.D.",
    years: 20,
    fees: [190, 230],
    full: true,
    participants: ["individuals", "couples", "groups"],
    ages: ["adults"],
    specialties: ["addiction", "depression", "relationships", "stress"],
    approaches: ["cbt", "act", "family_systems"],
    languages: ["English"],
    education: [["Psy.D. Clinical Psychology", "Pacific University", 2004]],
    locations: [{ city: "Salt Lake City", state: "UT", zip: "84111", formats: both, practice: "Wasatch Recovery Psychology", address: "175 S Main St, Suite 1100" }],
    who: "I work with adults and couples affected by addiction, including family members who love someone in recovery and are worn out from worrying.",
    about: "I've worked in treatment programs and private practice for twenty years. I'm compassionate and steady, and I believe recovery looks different for everyone. My practice is currently full.",
  },
  {
    photo: "photo-1648474484044-bb82df2f5a1f",
    first: "Christopher",
    last: "Lane",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Professional Counselor, LPC",
    years: 7,
    fees: [140, 170],
    participants: ["individuals", "couples"],
    ages: ["adults"],
    specialties: ["stress", "anxiety", "relationships", "burnout"],
    approaches: ["cbt", "solution_focused"],
    languages: ["English"],
    education: [["M.Ed. Counseling", "University of Missouri–St. Louis", 2017]],
    locations: [{ city: "St. Louis", state: "MO", zip: "63108", formats: both, practice: "Central West End Counseling", address: "4625 Lindell Blvd, Suite 300" }],
    who: "I work with adults under pressure — first responders, military spouses, people in high-stakes jobs — and with couples who've drifted into living parallel lives.",
    about: "I'm calm, direct and goal-focused. We'll agree on what you want to change and check in regularly on whether it's working.",
  },
  {
    photo: "photo-1738566061505-556830f8b8f5",
    first: "Alex",
    last: "Rivera",
    pronouns: "they/them",
    gender: "non_binary",
    title: "Licensed Marriage & Family Therapist, LMFT",
    years: 6,
    fees: [120, 150],
    sliding: true,
    participants: ["individuals", "couples"],
    ages: ["teens", "adults"],
    specialties: ["lgbtq", "cultural_identity", "relationships", "trauma_ptsd"],
    approaches: ["narrative", "somatic", "attachment_based"],
    languages: ["English", "Spanish"],
    education: [["M.A. Counseling (MFT)", "University of New Mexico", 2018]],
    locations: [{ city: "Albuquerque", state: "NM", zip: "87102", formats: both, practice: "Nob Hill Affirming Therapy", address: "3500 Central Ave SE, Suite 2" }],
    who: "I work with LGBTQ+ and Two-Spirit people, Latinx and Indigenous clients, and couples and relationships of all shapes looking for an affirming therapist who understands their context.",
    about: "I'm a queer therapist and approach our work with curiosity, respect for culture and attention to how stress lives in the body. Sessions in English or Spanish.",
  },
  {
    photo: "photo-1774437790865-76bfb73d7166",
    first: "Rohan",
    last: "Desai",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Clinical Social Worker, LCSW",
    years: 8,
    fees: [150, null],
    participants: ["individuals"],
    ages: ["teens", "adults"],
    specialties: ["anxiety", "ocd", "depression", "cultural_identity"],
    approaches: ["cbt", "act", "mindfulness"],
    languages: ["English", "Hindi", "Urdu"],
    education: [["M.S.W.", "Loyola University Chicago", 2016]],
    locations: [{ city: "Evanston", state: "IL", zip: "60201", formats: both, practice: "North Shore Anxiety Counseling", address: "1603 Orrington Ave, Suite 1050" }],
    who: "I work with teens and adults with anxiety and OCD, and with South Asian clients navigating family, faith and identity.",
    about: "I'm structured but flexible. We'll build skills for managing anxious thoughts and make room for the bigger questions underneath them.",
  },
  {
    photo: "photo-1758600432264-b8d2a0fd7d83",
    first: "Thomas",
    last: "Yamamoto",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Psychologist, Ph.D.",
    years: 32,
    fees: [200, null],
    participants: ["individuals", "couples"],
    ages: ["adults", "seniors"],
    specialties: ["depression", "grief_loss", "life_transitions", "chronic_illness"],
    approaches: ["psychodynamic", "act", "mindfulness"],
    languages: ["English", "Japanese"],
    education: [["Ph.D. Clinical Psychology", "University of Hawaiʻi at Mānoa", 1992]],
    locations: [{ city: "Honolulu", state: "HI", zip: "96813", formats: both, practice: "Kakaʻako Psychology", address: "1001 Bishop St, Suite 2100" }],
    who: "I work with adults in midlife and later life facing depression, loss, illness and the question of what comes next.",
    about: "After three decades of practice, I've learned to slow down and listen. Sessions in English or Japanese.",
  },
  {
    photo: "photo-1764173039051-987d1639b9d5",
    first: "Robert",
    last: "Feldman",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Independent Social Worker (Supervisor), LISW-S",
    years: 25,
    fees: [120, null],
    sliding: true,
    participants: ["individuals", "groups"],
    ages: ["adults", "seniors"],
    specialties: ["addiction", "depression", "grief_loss", "relationships"],
    approaches: ["cbt", "person_centered", "solution_focused"],
    languages: ["English"],
    education: [["M.S.W.", "Case Western Reserve University", 1999]],
    locations: [{ city: "Cleveland", state: "OH", zip: "44113", formats: both, practice: "Ohio City Recovery Counseling", address: "1900 W 25th St, Suite 2" }],
    who: "I work with adults in recovery from alcohol and drug use, and with men over 50 facing retirement, divorce or loss and wondering who they are now.",
    about: "I've been sober for over twenty years and a social worker for twenty-five. I bring hope, humor and practical tools, without judgment.",
  },
  {
    photo: "photo-1758612897972-dba54225048a",
    first: "Walter",
    last: "Hughes",
    pronouns: "he/him",
    gender: "male",
    title: "Licensed Clinical Psychologist, Ph.D.",
    years: 38,
    fees: [180, null],
    participants: ["individuals"],
    ages: ["adults", "seniors"],
    specialties: ["anxiety", "depression", "sleep", "life_transitions"],
    approaches: ["cbt", "act"],
    languages: ["English"],
    education: [["Ph.D. Clinical Psychology", "University of Virginia", 1986]],
    locations: [{ city: "Richmond", state: "VA", zip: "23220", formats: both, practice: "The Fan Psychology", address: "1802 Monument Ave, Suite 1" }],
    who: "I work with adults of all ages with anxiety, depression and insomnia, and with older adults adjusting to retirement and changes in health.",
    about: "I'm a seasoned psychologist with a fondness for practical, well-tested tools and a good conversation. I'm patient, and I'll explain everything as we go.",
  },
];
