// Writes the SQL that seeds the 50 sample providers into a migration file:
//   npx tsx scripts/sample-seed-sql.ts drizzle/0007_sample_providers.sql
// Each provider is one statement that does nothing if their account already
// exists, and nothing at all once an admin has removed the samples.
import { randomInt } from "node:crypto";
import { writeFileSync } from "node:fs";
import { SAMPLE_PROVIDERS } from "../src/server/directory/sample-data";
import { sampleRows } from "../src/server/directory/sample-rows";

const out = process.argv[2];
if (!out) throw new Error("Usage: tsx scripts/sample-seed-sql.ts <file.sql>");

const ALPHABET = "abcdefghjkmnpqrstuvwxyz23456789";
const used = new Set<string>();
const publicId = () => {
  let id = "";
  do id = Array.from({ length: 8 }, () => ALPHABET[randomInt(ALPHABET.length)]).join("");
  while (used.has(id));
  used.add(id);
  return id;
};

type Value = string | number | boolean | null | undefined;
// Line breaks are written as \n escapes (E'...'), so the bios come out the
// same whatever line endings a checkout uses.
const quote = (v: string) =>
  /[\n\\]/.test(v) ? `E'${v.replace(/\\/g, "\\\\").replace(/'/g, "''").replace(/\r?\n/g, "\\n")}'` : `'${v.replace(/'/g, "''")}'`;
const lit = (v: Value) =>
  v == null ? "NULL" : typeof v === "boolean" ? String(v).toUpperCase() : typeof v === "number" ? String(v) : quote(v);
const textArray = (a: string[]) => (a.length ? `ARRAY[${a.map(lit).join(", ")}]::text[]` : "'{}'::text[]");
const jsonb = (o: unknown) => `${lit(JSON.stringify(o))}::jsonb`;

const statements = SAMPLE_PROVIDERS.map((s, i) => {
  const r = sampleRows(s, i);
  const p = r.profile;
  const locations = r.locations
    .map((l) => `(${[lit(l.state), lit(l.city), lit(l.zip), lit(l.practiceName), lit(l.address), textArray(l.formats), lit(l.isPrimary), lit(l.sortOrder)].join(", ")})`)
    .join(",\n    ");
  const licenses = r.licenses.map((l) => `(${[lit(l.state), lit(l.licenseNumber), lit(l.issuingBody)].join(", ")})`).join(",\n    ");
  return `-- ${r.user.name}
WITH guard AS (
  SELECT 1 WHERE NOT EXISTS (SELECT 1 FROM "audit_log" WHERE "action" = 'samples.removed')
), u AS (
  INSERT INTO "user" ("id", "name", "email", "email_verified", "role", "first_name", "last_name")
  SELECT gen_random_uuid()::text, ${lit(r.user.name)}, ${lit(r.user.email)}, TRUE, 'provider', ${lit(r.user.firstName)}, ${lit(r.user.lastName)} FROM guard
  ON CONFLICT ("email") DO NOTHING
  RETURNING "id"
), p AS (
  INSERT INTO "provider_profile" ("id", "user_id", "public_id", "status", "is_sample", "external_photo_url", "onboarding_step", "first_name", "last_name", "title_credentials", "pronouns", "banner_style", "who_you_work_with", "about", "session_participants", "age_groups", "specialties", "primary_specialty", "approaches", "languages", "gender", "fee_individual", "fee_couples", "sliding_scale", "accepting_new_clients", "education", "npi_number", "years_experience", "submitted_at", "approved_at")
  SELECT gen_random_uuid()::text, u."id", ${lit(publicId())}, 'approved', TRUE, ${lit(p.externalPhotoUrl)}, ${lit(p.onboardingStep)}, ${lit(p.firstName)}, ${lit(p.lastName)}, ${lit(p.titleCredentials)}, ${lit(p.pronouns)}, ${lit(p.bannerStyle)}, ${lit(p.whoYouWorkWith)}, ${lit(p.about)}, ${textArray(p.sessionParticipants)}, ${textArray(p.ageGroups)}, ${textArray(p.specialties)}, ${lit(p.primarySpecialty)}, ${textArray(p.approaches)}, ${textArray(p.languages)}, ${lit(p.gender)}, ${lit(p.feeIndividual)}, ${lit(p.feeCouples)}, ${lit(p.slidingScale)}, ${lit(p.acceptingNewClients)}, ${jsonb(p.education)}, ${lit(p.npiNumber)}, ${lit(p.yearsExperience)}, now() - interval '${r.approvedDaysAgo + 2} days', now() - interval '${r.approvedDaysAgo} days'
  FROM u
  RETURNING "id"
), l AS (
  INSERT INTO "provider_location" ("id", "profile_id", "state", "city", "zip", "practice_name", "address", "formats", "is_primary", "sort_order")
  SELECT gen_random_uuid()::text, p."id", v.state, v.city, v.zip, v.practice_name, v.address, v.formats, v.is_primary, v.sort_order
  FROM p, (VALUES
    ${locations}
  ) AS v(state, city, zip, practice_name, address, formats, is_primary, sort_order)
)
INSERT INTO "provider_license" ("id", "profile_id", "state", "license_number", "issuing_body", "status")
SELECT gen_random_uuid()::text, p."id", v.state, v.license_number, v.issuing_body, 'verified'
FROM p, (VALUES
    ${licenses}
  ) AS v(state, license_number, issuing_body);`;
});

const header = `-- The 50 sample providers (src/server/directory/sample-data.ts), so a new
-- database shows a populated directory. Generated by scripts/sample-seed-sql.ts.
-- Skips anyone who already exists, and everything once an admin has removed
-- the samples (Admin → All providers).
`;
writeFileSync(out, header + statements.join("\n--> statement-breakpoint\n") + "\n");
console.log(`Wrote ${statements.length} sample providers to ${out}`);
